version: '3.7'
services:
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-7.0-latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: 192.168.6.114
      DB_SERVER_PORT: 5434
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
    ports:
      - "10051:10051"
    volumes:
      - zabbix-server-logs:/var/log/zabbix
    restart: unless-stopped
    networks:
      - zabbix-net

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-7.0-latest
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: 192.168.6.114
      DB_SERVER_PORT: 5434
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      ZBX_SERVER_HOST: zabbix-server
    depends_on:
      - zabbix-server
    ports:
      - "8080:8080"
    volumes:
      - zabbix-web-data:/usr/share/zabbix
    restart: unless-stopped
    networks:
      - zabbix-net

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-7.0-latest
    container_name: zabbix-agent
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_HOSTNAME: zabbix-agent
    depends_on:
      - zabbix-server
    restart: unless-stopped
    networks:
      zabbix-net:
        ipv4_address: 172.30.0.100

volumes:
  zabbix-server-logs:
  zabbix-web-data:

networks:
  zabbix-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
